### ISSUE TITLE
Poboljsanja

### ISSUE THREAD

**Issue by miki995** [Innovic-io/jahorina-ski-hike#1]
Pogledao sam aplikaciju i stvarno je odlicna,ali sam naisao na neke prepreke, stoga imam par sugestija.

- Omoguciti satelitski pogled radi boljeg pregleda i snalazenja korisnika,
- Omoguciti biranje kategorija bez vracanja na pocetni ekran, jer odvraca korisnike od sajta,
- Mobilne aplikacije bi dobro dosle.

**Comment by vladotesanovic** [comment]
Hvala Miroslave na sugestijama,

Aplikacija je djelo @mbrckalo-innovic Milana, u procesu učenja odredjenih tehnologija.

Možda nekom novom junior developer-u damo da to popravi, ili jednostavno ako imaš vreman možeš i ti napraviti PR sa tim izmjenama.

Rado ćemo prihvatiti i objaviti promjene.

**Comment by miki995** [comment]
Hvala na odgovoru, 
Napravio sam mobilnu aplikaciju za android OS, ali nije ogranicena na jedan grad vec RS
---> https://github.com/miki995/MapRS <---
Pozdrav
